Repository OFP-CDA-Mulhouse-2020/parisportif2, pull requests merged in 2021-02, with the labels that each got.

#98 Feature/bank account file attachment
  src/Controller/BankAccountController.php
  src/Factory/BankAccountFileFactory.php
  src/Form/BankAccountType.php
  src/Form/IdentityType.php
  src/FormHandler/BankAccountHandler.php
  tests/Data/rib.jpg
  tests/Functional/BankAccountControllerTest.php
  tests/Functional/UserProfileInformationControllerTest.php
Labels: enhancement

#101 Feature/edit amount bet in cart
  src/Controller/CartController.php
  templates/ticket/_ticket.html.twig
Labels: enhancement

#102 Feature/sport pages mk
  migrations/Version20210201130843.php
  migrations/Version20210201132036.php
  src/Controller/SportsController.php
  src/DataFixtures/BetFixtures.php
  src/DataFixtures/CompetitionFixtures.php
  src/DataFixtures/Sports/Formula1/SportFormulaOneFixtures.php
  src/Entity/Competition.php
  src/Entity/Sport.php
  src/Repository/BetRepository.php
  src/Repository/CompetitionRepository.php
  templates/partials/header.html.twig
  templates/sports/_sports_bet.html.twig
  templates/sports/index.html.twig
Labels: enhancement

#104 Feature/mailer service
  .env
  .env.test
  composer.json
  composer.lock
  config/bundles.php
  config/packages/reset_password.yaml
  config/packages/verify_email.yaml
  document/activity.md
  migrations/Version20210201102912.php
  src/Controller/RegistrationController.php
  src/Controller/ResetPasswordController.php
  src/Controller/UserProfileLoginController.php
  src/Entity/ResetPasswordRequest.php
  src/Form/ChangePasswordFormType.php
  src/Form/ResetPasswordRequestFormType.php
  src/FormHandler/EditEmailHandler.php
  src/FormHandler/RegisterHandler.php
  src/Repository/ResetPasswordRequestRepository.php
  src/Service/MailerService.php
  symfony.lock
  templates/email/edit_email_confirmation_email.html.twig
  templates/email/register_confirmation_email.html.twig
  templates/registration/register.html.twig
  templates/reset_password/check_email.html.twig
  templates/reset_password/email.html.twig
  templates/reset_password/request.html.twig
  templates/reset_password/reset.html.twig
  templates/security/login.html.twig
  tests/Functional/RegisterControllerTest.php
  tests/Functional/ResetPasswordControllerTest.php
  tests/Functional/UserProfileLoginControllerTest.php
  tests/Unit/MailerServiceTest.php
Labels: enhancement

#105 2021-02-03 #90 code review for phpstan
  migrations/Version20210203090346.php
  src/Controller/BankAccountController.php
  src/Controller/CartController.php
  src/Controller/HomeController.php
  src/Controller/PaymentController.php
  src/Controller/RegistrationController.php
  src/Controller/UserProfileInformationController.php
  src/Controller/UserProfileLoginController.php
  src/Controller/WalletController.php
  src/DataFixtures/CompetitionFixtures.php
  src/Entity/Sport.php
  src/Entity/Team.php
  src/FormHandler/AddMoneyHandler.php
  src/FormHandler/BankAccountHandler.php
  src/FormHandler/EditIdentityHandler.php
  src/FormHandler/EditPasswordHandler.php
  src/FormHandler/WithdrawMoneyHandler.php
  src/Service/DatabaseService.php
  src/Service/MailerService.php
  tests/Functional/BankAccountControllerTest.php
  tests/Functional/UserProfileInformationControllerTest.php
Labels: improvement

#106 2021-02-04 #103 New fixtures
  migrations/Version20210201130843 2.php
  migrations/Version20210201132036 2.php
  src/DataFixtures/BetFixtures.php
  src/DataFixtures/EventFixtures.php
Labels: enhancement

#108 Feature/user account suspension management
  src/Controller/UserProfileController.php
  src/Entity/User.php
  src/Form/SuspendAccountType.php
  templates/security/login.html.twig
  templates/user_profile/activation.html.twig
  templates/user_profile/suspend.html.twig
  tests/Functional/UserProfileControllerTest.php
  tests/Unit/UserTest.php
Labels: enhancement

#110 Feature/twig template
  document/activity.md
  document/diagram_class/archive/parisportif_11.plantuml
  document/diagram_class/parisportif_12.plantuml
  migrations/Version20210201102912.php
  migrations/Version20210201130843 2.php
  migrations/Version20210201130843.php
  migrations/Version20210201132036 2.php
  migrations/Version20210201132036.php
  migrations/Version20210203090346.php
  migrations/Version20210204125129.php
  src/Controller/CartController.php
  src/Controller/EventController.php
  src/Controller/HomeController.php
  src/Controller/SportController.php
  src/Controller/SportsController.php
  src/DataFixtures/BetFixtures.php
  src/DataFixtures/CompetitionFixtures.php
  src/DataFixtures/EventFixtures.php
  src/DataFixtures/Sports/Basketball/CharlotteHornets/CharlotteHornetsPlayersFixtures.php
  src/DataFixtures/Sports/Basketball/CharlotteHornets/CharlotteHornetsTeamFixtures.php
  src/DataFixtures/Sports/Basketball/DetroitPistons/DetroitPistonsPlayersFixtures.php
  src/DataFixtures/Sports/Basketball/DetroitPistons/DetroitPistonsTeamFixtures.php
  src/DataFixtures/Sports/Basketball/SportBasketballFixtures.php
  src/DataFixtures/TypeOfBetFixtures.php
  src/Entity/Competition.php
  src/Repository/BetRepository.php
  templates/bet/_football_bet.html.twig
  templates/bet/_home_bet.html.twig
  templates/bet/_sport_bet.html.twig
  templates/event/event.html.twig
  templates/home/home.html.twig
  templates/partials/_aside_left.html.twig
  templates/partials/_aside_right.html.twig
  templates/partials/_carousel.html.twig
  templates/partials/_footer.html.twig
  templates/partials/_header.html.twig
  templates/sport/_nav_left.html.twig
  templates/sport/sport.html.twig
  templates/sports/index.html.twig
  templates/ticket/_ticket.html.twig
  templates/user_profile/user_profile.html.twig
  tests/Functional/HomeControllerTest.php
Labels: enhancement

#111 Feature/webpack panther
  .gitignore
  assets/app.js
  assets/bootstrap.js
  assets/controllers.json
  assets/controllers/hello_controller.js
  assets/styles/app.css
  composer.json
  composer.lock
  config/bundles.php
  config/packages/assets.yaml
  config/packages/prod/webpack_encore.yaml
  config/packages/test/webpack_encore.yaml
  config/packages/webpack_encore.yaml
  document/diagram_class/archive/parisportif_11.plantuml
  document/diagram_class/parisportif_12.plantuml
  migrations/Version20210205133217.php
  package-lock.json
  package.json
  phpcs.xml.dist
  symfony.lock
  templates/base.html.twig
  webpack.config.js
Labels: enhancement

#113 Feature/ci correction
  .github/workflows/ci.yml
Labels: bug

#114 Feature/panther
  composer.json
  composer.lock
  phpunit.xml.dist
  symfony.lock
  tests/Functional/JsControllerTest.php
Labels: enhancement

#118 Feature/easy admin mk
  public/css/admin.css
  src/Admin/Field/MapMkField.php
  src/Controller/Admin/DashboardController.php
  src/Controller/Admin/UserCrudController.php
  src/Controller/Admin/WalletCrudController.php
  src/Entity/Wallet.php
  templates/admin/field/map.html.twig
  templates/bundle/EasyAdminBundle/crud/detail.html.twig
  templates/bundle/EasyAdminBundle/crud/field/country.html.twig
  templates/bundle/EasyAdminBundle/crud/field/text.html.twig
  templates/bundle/EasyAdminBundle/crud/index.html.twig
  templates/bundle/EasyAdminBundle/label/null.html.twig
  templates/bundle/EasyAdminBundle/layout.html.twig
  templates/bundle/EasyAdminBundle/menu.html.twig
  templates/bundle/EasyAdminBundle/page/content.html.twig
  templates/bundle/EasyAdminBundle/page/login.html.twig
Labels: enhancement

#119 Feature/admin part
  assets/app.js
  assets/app/App.js
  assets/app/AsideLeft.js
  assets/app/AsideRight.js
  assets/app/Carousel.js
  assets/app/CartContext.js
  assets/app/Middle.js
  assets/betBoard/components/BetBoard.js
  assets/betBoard/components/EventList.js
  assets/betBoard/components/Filter.js
  assets/betBoard/components/OddsList.js
  assets/cart/components/Cart.js
  assets/cart/components/ItemList.js
  assets/cart/data/cart.json
  assets/js/display.js
  document/activity.md
  package-lock.json
  package.json
  src/Admin/Field/MapField.php
  src/Admin/Field/OddsField.php
  src/Controller/Admin/BetCrudController.php
  src/Controller/ApiController.php
  src/DataFixtures/BetFixtures.php
  src/Dto/BetDto.php
  src/Dto/ResultDto.php
  src/Entity/Bet.php
  src/Entity/Cart.php
  src/Entity/Competition.php
  src/Entity/Event.php
  src/Entity/Item.php
  src/Entity/Sport.php
  src/Entity/Team.php
  src/Entity/TypeOfBet.php
  src/Form/BetType.php
  src/Form/ResultType.php
  templates/api/index.html.twig
  templates/bet/_football_bet.html.twig
  templates/bet/_home_bet.html.twig
  templates/bundles/EasyAdminBundle/crud/custom_edit.html.twig
  templates/partials/_header.html.twig
  templates/ticket/_ticket.html.twig
  templates/user_profile/user_profile.html.twig
  tests/Functional/JsControllerTest.php
  webpack.config.js
Labels: enhancement

#124 Feature/js on information profile
  assets/app.js
  assets/js/profileInformation.js
  assets/styles/app.css
  src/Controller/UserProfileInformationController.php
  src/Form/AddressDisabledType.php
  src/Form/IdentityDisabledType.php
  templates/user_profile/information.html.twig
  tests/Functional/UserProfileControllerTest.php
  tests/Functional/UserProfileInformationControllerJsTest.php
  tests/Functional/UserProfileInformationControllerTest.php
Labels: enhancement

#125 Feature/admin2
  assets/app.js
  assets/app/App.js
  assets/js/badge.js
  assets/styles/app.css
  document/diagram_class/parisportif_12.plantuml
  migrations/Version20210216162921.php
  public/css/admin.css
  src/Admin/Field/MapMkField.php
  src/Controller/Admin/BankAccountCrudController.php
  src/Controller/Admin/BankAccountFileCrudController.php
  src/Controller/Admin/BetCrudController.php
  src/Controller/Admin/CardIdFileCrudController.php
  src/Controller/Admin/DashboardController.php
  src/Controller/Admin/PaymentCrudController.php
  src/Controller/Admin/TypeOfPaymentCrudController.php
  src/Controller/Admin/UserCrudController.php
  src/Controller/Admin/WalletCrudController.php
  src/Controller/Admin/WebsiteWalletCrudController.php
  src/DataFixtures/CompetitionFixtures.php
  src/DataFixtures/WebsiteWalletFixtures.php
  src/Dto/GenerateBetPaymentDto.php
  src/Entity/BankAccount.php
  src/Entity/BankAccountFile.php
  src/Entity/CardIdFile.php
  src/Entity/Event.php
  src/Entity/TypeOfPayment.php
  src/Entity/User.php
  src/Entity/Wallet.php
  src/Entity/WebsiteWallet.php
  src/Form/ResultEventType.php
  src/Form/ResultFieldType.php
  src/FormHandler/BankAccountHandler.php
  src/Repository/EventRepository.php
  templates/bundle/EasyAdminBundle/crud/detail.html.twig
  templates/bundle/EasyAdminBundle/crud/field/country.html.twig
  templates/bundle/EasyAdminBundle/crud/field/text.html.twig
  templates/bundle/EasyAdminBundle/label/null.html.twig
  templates/bundle/EasyAdminBundle/layout.html.twig
  templates/bundle/EasyAdminBundle/menu.html.twig
  templates/bundle/EasyAdminBundle/page/content.html.twig
  templates/bundle/EasyAdminBundle/page/login.html.twig
  templates/bundles/EasyAdminBundle/crud/custom_form_bet_result.html.twig
  templates/bundles/EasyAdminBundle/crud/custom_index.html.twig
  templates/bundles/EasyAdminBundle/welcome.html.twig
  templates/cart/_cart.html.twig
  templates/partials/_aside_right.html.twig
  templates/partials/_header.html.twig
  templates/user_profile/user_profile.html.twig
  tests/Functional/JsControllerTest.php
  tests/Functional/UserProfileControllerTest.php
  tests/Unit/BankAccountTest.php
  tests/Unit/UserTest.php
  webpack.config.js
Labels: enhancement

#127 Feature/controller part
  assets/app.js
  assets/app/App.js
  assets/app/CartContext.js
  assets/app/Home.js
  assets/app/SelectedEvent.js
  assets/app/SelectedSport.js
  assets/app/cart/Cart.js
  assets/app/cart/ItemList.js
  assets/app/eventBetBoard/EventBetBoard.js
  assets/app/eventBetBoard/EventList.js
  assets/app/eventBetBoard/OddsList.js
  assets/app/homeBetBoard/EventList.js
  assets/app/homeBetBoard/Filter.js
  assets/app/homeBetBoard/HomeBetBoard.js
  assets/app/homeBetBoard/OddsList.js
  assets/app/partials/AsideLeft.js
  assets/app/partials/AsideRight.js
  assets/app/partials/Carousel.js
  assets/app/partials/Middle.js
  assets/app/partials/NavLeft.js
  assets/app/sportBetBoard/SportBetBoard.js
  assets/app/sportBetBoard/SportEventList.js
  assets/app/sportBetBoard/SportOddsList.js
  assets/betBoard/components/BetBoard.js
  assets/betBoard/components/OddsList.js
  assets/cart/data/cart.json
  assets/js/display.js
  assets/styles/app.css
  document/activity.md
  package-lock.json
  package.json
  src/Controller/Admin/BetCrudController.php
  src/Controller/ApiController.php
  src/Controller/CartController.php
  src/Controller/EventController.php
  src/Controller/PaymentController.php
  src/Dto/GenerateBetPaymentDto.php
  src/Dto/ResultDto.php
  src/Entity/Bet.php
  src/Entity/Event.php
  src/Factory/ItemFactory.php
  src/Factory/PaymentFactory.php
  src/Factory/TypeOfPaymentFactory.php
  src/Form/ResultType.php
  src/Repository/ItemRepository.php
  src/Service/GenerateBetPaymentService.php
  templates/bet/_home_bet.html.twig
  templates/bet/_sport_bet.html.twig
  templates/cart/cart_history.html.twig
  templates/partials/_header.html.twig
  tests/Functional/HomeControllerTest.php
  webpack.config.js
Labels: enhancement

#126 Feature/Js on login page #123
  assets/app.js
  assets/controllers/hello_controller.js
  assets/js/login.js
  assets/styles/app.css
  src/Controller/UserProfileLoginController.php
  src/Form/EditEmailDisableType.php
  templates/user_profile/login.html.twig
  tests/Functional/UserProfileLoginControllerTest.php
Labels: enhancement

#130 Feature/design interface app
  config/packages/twig.yaml
  public/images/footer/anj.jpg
  public/images/footer/icon_jouons-responsable.png
  public/images/footer/interdiction-18.png
  public/images/menu_pictos/basketball.png
  public/images/menu_pictos/cyclisme.png
  public/images/menu_pictos/cyclist.png
  public/images/menu_pictos/f1.png
  public/images/menu_pictos/football.png
  public/images/menu_pictos/formule1-2.png
  public/images/menu_pictos/formule1.png
  public/images/menu_pictos/handball.png
  public/images/menu_pictos/home.png
  public/images/menu_pictos/live.png
  public/images/menu_pictos/search.png
  public/images/menu_pictos/tennis.png
  public/images/menu_pictos/watch.png
  src/Form/AddressDisabledType.php
  src/Form/AddressType.php
  src/Form/IdentityDisabledType.php
  src/Form/IdentityType.php
  src/Form/LoginType.php
  src/Form/RegistrationType.php
  src/Form/ResetPasswordRequestFormType.php
  templates/base.html.twig
  templates/form_layout/login-register_layout.html.twig
  templates/partials/_footer.html.twig
  templates/partials/_header.html.twig
  templates/partials/_header_logo.html.twig
  templates/registration/register.html.twig
  templates/reset_password/check_email.html.twig
  templates/reset_password/request.html.twig
  templates/reset_password/reset.html.twig
  templates/security/login.html.twig
  templates/user_profile/activation.html.twig
  templates/user_profile/information.html.twig
  templates/user_profile/login.html.twig
  templates/user_profile/suspend.html.twig
  templates/user_profile/user_profile.html.twig
  templates/wallet/balance.html.twig
  templates/wallet/bank-account.html.twig
  templates/wallet/limit-amount.html.twig
  templates/wallet/withdraw-money.html.twig
  tests/Functional/JsControllerTest.php
  tests/Functional/LoginControllerTest.php
Labels: enhancement
