Repository OFP-CDA-Mulhouse-2020/parisportif2, pull requests merged in 2021-01, with the labels that each got.

#59 Feature/sport player team entities
  document/diagram_class/lastuml.plantuml
  phpstan.neon
  phpunit-watcher.yml
  src/Entity/Competition.php
  src/Entity/Event.php
  src/Entity/Player.php
  src/Entity/Sport.php
  src/Entity/Team.php
  src/Repository/PlayerRepository.php
  src/Repository/SportRepository.php
  src/Repository/TeamRepository.php
  tests/Unit/CompetitionTest.php
  tests/Unit/EventTest.php
  tests/Unit/PlayerTest.php
  tests/Unit/SportTest.php
  tests/Unit/TeamTest.php
Labels: enhancement

#60 Feature/relation sport user
  README.md
  document/activity.md
  document/diagram_class/archive/parisportif.plantuml
  document/diagram_class/archive/parisportif_2.plantuml
  document/diagram_class/archive/parisportif_3.plantuml
  document/diagram_class/archive/parisportif_4 copy.plantuml
  document/diagram_class/archive/parisportif_5.plantuml
  document/diagram_class/archive/parisportif_6 copy.plantuml
  document/diagram_class/archive/parisportif_6.plantuml
  document/diagram_class/archive/parisportif_7.plantuml
  document/diagram_class/archive/parisportif_8.plantuml
  document/diagram_class/archive/parisportif_9.plantuml
  document/diagram_class/lastuml.plantuml
  migrations/Version20210104131059.php
  migrations/Version20210104134149.php
  phpunit-watcher.yml
  src/Entity/Bet.php
  src/Entity/Event.php
  src/Entity/Player.php
  src/Entity/Team.php
  tests/Functional/LoginControllerTest.php
  tests/Unit/AddressTest.php
  tests/Unit/EventTest.php
  tests/Unit/PlayerTest.php
  tests/Unit/SportTest.php
  tests/Unit/TeamTest.php
  tests/Unit/TypeOfPaymentTest.php
  tests/Unit/WebsiteWalletTest.php
Labels: enhancement

#62 Feature/homepage #58
  templates/home/home.html.twig
  templates/home_base.html.twig
  templates/partials/footer.html.twig
  templates/partials/header.html.twig
  tests/Functional/HomeControllerTest.php
Labels: enhancement

#63 Feature/user profile
  src/Controller/RegistrationController.php
  src/Controller/UserProfileController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Form/AddressType.php
  src/Form/EditEmailType.php
  src/Form/EditPasswordType.php
  src/Form/IdentityType.php
  src/Form/LoginType.php
  src/Form/RegistrationType.php
  templates/home_base2.html.twig
  templates/security/login.html.twig
  templates/user_profile/activation.html.twig
  templates/user_profile/connexion.html.twig
  templates/user_profile/information.html.twig
  templates/user_profile/suspend.html.twig
  templates/user_profile/user_profile.html.twig
  tests/Functional/LoginControllerTest.php
  tests/Functional/RegisterControllerTest.php
  tests/Functional/UserProfileControllerTest.php
  tests/Unit/UserTest.php
Labels: enhancement

#65 Feature/user email #57
  src/Controller/UserProfileController.php
  src/Controller/UserProfileLoginController.php
  src/Form/EditEmailType.php
  templates/user_profile/connexion.html.twig
  templates/user_profile/login.html.twig
  templates/user_profile/user_profile.html.twig
  tests/Functional/UserProfileControllerTest.php
  tests/Functional/UserProfileLoginControllerTest.php
Labels: enhancement

#67 2021-01-13 #57 editing UserProfileInformation address part done
  src/Controller/UserProfileController.php
  src/Controller/UserProfileInformationController.php
  src/Form/AddressType.php
  src/Form/IdentityType.php
  templates/home/home.html.twig
  templates/user_profile/information.html.twig
Labels: enhancement

#68 Feature/user wallet #64
  document/activity.md
  src/Controller/BankAccountController.php
  src/Controller/WalletController.php
  src/DataFixtures/AddressFixtures.php
  src/DataFixtures/BankAccountFixtures.php
  src/DataFixtures/PaymentFixtures.php
  src/DataFixtures/TypeOfPaymentFixtures.php
  src/DataFixtures/UserFixtures.php
  src/DataFixtures/WalletFixtures.php
  src/Entity/BankAccount.php
  src/Entity/Payment.php
  src/Form/BankAccountType.php
  src/Form/PaymentType.php
  src/Form/WalletType.php
  templates/user_profile/user_profile.html.twig
  templates/wallet/add-money.html.twig
  templates/wallet/balance.html.twig
  templates/wallet/bank-account.html.twig
  templates/wallet/limit-amount.html.twig
  templates/wallet/withdraw-money.html.twig
  tests/Functional/BankAccountControllerTest.php
  tests/Functional/WalletControllerTest.php
Labels: enhancement

#71 Feature/user wallet2 #64
  src/Controller/BankAccountController.php
  src/Controller/WalletController.php
  src/Factory/PaymentFactory.php
  src/Factory/TypeOfPaymentFactory.php
  src/Form/AddMoneyType.php
  src/Form/WithdrawMoneyType.php
  src/FormHandler/AddMoneyHandler.php
  src/FormHandler/BankAccountHandler.php
  src/FormHandler/WalletHandler.php
  src/FormHandler/WithdrawMoneyHandler.php
  src/Repository/PaymentRepository.php
  templates/wallet/add-money.html.twig
  templates/wallet/bank-account.html.twig
  templates/wallet/limit-amount.html.twig
  templates/wallet/withdraw-money.html.twig
  tests/Functional/WalletControllerTest.php
Labels: enhancement

#75 Feature/user profile information 2
  .gitignore
  config/services.yaml
  migrations/Version20210115093103.php
  src/Controller/UserProfileInformationController.php
  src/DataFixtures/Sports/Basket/CharlotteHornets/CharlotteHornetsPlayersFixtures.php
  src/DataFixtures/Sports/Basket/CharlotteHornets/CharlotteHornetsTeamFixtures.php
  src/DataFixtures/Sports/Basket/DetroitPistons/DetroitPistonsPlayersFixtures.php
  src/DataFixtures/Sports/Basket/DetroitPistons/DetroitPistonsTeamFixtures.php
  src/DataFixtures/Sports/Basket/SportBasketFixtures.php
  src/DataFixtures/Sports/Football/Lyon/LyonPlayersFixtures.php
  src/DataFixtures/Sports/Football/Lyon/LyonTeamFixtures.php
  src/DataFixtures/Sports/Football/SportFootballFixtures.php
  src/DataFixtures/Sports/Football/Strasbourg/StrasbourgPlayersFixtures.php
  src/DataFixtures/Sports/Football/Strasbourg/StrasbourgTeamFixtures.php
  src/Entity/CardIdFile.php
  src/Entity/User.php
  src/Form/IdentityType.php
  src/Repository/CardIdFileRepository.php
  templates/user_profile/information.html.twig
  tests/Functional/CardIdFileControllerTest.php
  tests/Unit/CardIdFileTest.php
  tests/Unit/UserTest.php
Labels: enhancement

#76 Feature/easy admin #73
  composer.json
  composer.lock
  config/bundles.php
  document/activity.md
  src/Controller/Admin/DashboardController.php
  src/Controller/Admin/PlayerCrudController.php
  src/Controller/Admin/TeamCrudController.php
  src/Entity/Player.php
  src/Entity/Team.php
  src/FormHandler/WithdrawMoneyHandler.php
  symfony.lock
  tests/Functional/CardIdFileControllerTest.php
Labels: enhancement

#81 Feature/cart and payment controllers
  composer.json
  composer.lock
  githook/pre-commit.sh
  githook/setup.sh
  src/Controller/BetController.php
  src/Controller/CartController.php
  src/Controller/HomeController.php
  src/Controller/PaymentController.php
  src/DataFixtures/BetFixtures.php
  src/DataFixtures/TypeOfBetFixtures.php
  src/Entity/TypeOfBet.php
  src/Entity/Wallet.php
  src/Repository/PaymentRepository.php
  symfony.lock
  templates/bet/_home_bet.html.twig
  templates/home/home.html.twig
  templates/ticket/_ticket.html.twig
  tests/Functional/HomeControllerTest.php
  tests/Unit/BetTest.php
  tests/Unit/TypeOfBetTest.php
  tests/Unit/WalletTest.php
Labels: enhancement

#83 Feature/bet admin controller
  .env
  migrations/Version20201218132853.php
  migrations/Version20201222162151.php
  migrations/Version20210104131059.php
  migrations/Version20210104134149.php
  migrations/Version20210115093103.php
  migrations/Version20210121105512.php
  src/Controller/Admin/BetCrudController.php
  src/Controller/Admin/CompetitionCrudController.php
  src/Controller/Admin/DashboardController.php
  src/Controller/Admin/EventCrudController.php
  src/Controller/Admin/PlayerCrudController.php
  src/Controller/Admin/TeamCrudController.php
  src/Controller/Admin/TypeOfBetCrudController.php
  src/Controller/BetController.php
  src/Controller/HomeController.php
  src/Controller/PaymentController.php
  src/DataFixtures/BetFixtures.php
  src/DataFixtures/CompetitionFixtures.php
  src/DataFixtures/EventFixtures.php
  src/DataFixtures/Sports/Football/Lyon/LyonPlayersFixtures.php
  src/DataFixtures/Sports/Football/Strasbourg/StrasbourgPlayersFixtures.php
  src/Entity/Bet.php
  src/Entity/Event.php
  src/Entity/TypeOfBet.php
  src/Entity/Wallet.php
  templates/bet/_home_bet.html.twig
  templates/partials/header.html.twig
  templates/ticket/_ticket.html.twig
  tests/Unit/BetTest.php
Labels: enhancement

#89 2021-01-26 #88 correction service container on method editIdentity
  src/Controller/UserProfileInformationController.php
  src/FormHandler/EditIdentityHandler.php
Labels: bug

#93 2021-01-27 #91 UploaderFile service done with testing
  config/services.yaml
  src/Controller/UserProfileInformationController.php
  src/Factory/CardIdFileFactory.php
  src/FormHandler/EditIdentityHandler.php
  src/Service/FileUploaderService.php
  tests/Data/unknown.jpg
  tests/Functional/UserProfileInformationControllerTest.php
Labels: enhancement

#94 Feature/phpstan code review
  src/DataFixtures/BetFixtures.php
  src/DataFixtures/EventFixtures.php
  src/DataFixtures/PaymentFixtures.php
  src/DataFixtures/Sports/Basket/CharlotteHornets/CharlotteHornetsPlayersFixtures.php
  src/DataFixtures/Sports/Basket/CharlotteHornets/CharlotteHornetsTeamFixtures.php
  src/DataFixtures/Sports/Basket/DetroitPistons/DetroitPistonsPlayersFixtures.php
  src/DataFixtures/Sports/Basket/DetroitPistons/DetroitPistonsTeamFixtures.php
  src/DataFixtures/Sports/Football/Lyon/LyonPlayersFixtures.php
  src/DataFixtures/Sports/Football/Lyon/LyonTeamFixtures.php
  src/DataFixtures/Sports/Football/Strasbourg/StrasbourgPlayersFixtures.php
  src/DataFixtures/Sports/Football/Strasbourg/StrasbourgTeamFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Cart.php
  src/Entity/Item.php
  src/Repository/UserRepository.php
  tests/Functional/BankAccountControllerTest.php
  tests/Functional/HomeControllerTest.php
  tests/Functional/RegisterControllerTest.php
  tests/Functional/UserProfileControllerTest.php
  tests/Functional/UserProfileInformationControllerTest.php
  tests/Functional/UserProfileLoginControllerTest.php
  tests/Functional/WalletControllerTest.php
  tests/Unit/AddressTest.php
  tests/Unit/BankAccountFileTest.php
  tests/Unit/BankAccountTest.php
  tests/Unit/BetTest.php
  tests/Unit/CardIdFileTest.php
  tests/Unit/CartTest.php
  tests/Unit/CompetitionTest.php
  tests/Unit/EventTest.php
  tests/Unit/ItemTest.php
  tests/Unit/PaymentTest.php
  tests/Unit/PlayerTest.php
  tests/Unit/SportTest.php
  tests/Unit/TeamTest.php
  tests/Unit/TypeOfBetTest.php
  tests/Unit/UserTest.php
  tests/Unit/WalletTest.php
  tests/Unit/WebsiteWalletTest.php
Labels: improvement

#96 Feature/create service for database
  Makefile
  composer.json
  composer.lock
  migrations/Version20210126111508.php
  migrations/Version20210128123619.php
  src/Controller/RegistrationController.php
  src/Controller/UserProfileInformationController.php
  src/Controller/UserProfileLoginController.php
  src/FormHandler/AddMoneyHandler.php
  src/FormHandler/BankAccountHandler.php
  src/FormHandler/EditPasswordHandler.php
  src/FormHandler/LimitAmountWalletHandler.php
  src/FormHandler/WithdrawMoneyHandler.php
  src/Service/DatabaseService.php
  templates/user_profile/information.html.twig
  templates/user_profile/login.html.twig
Labels: enhancement
